baseurl = "/"
title = "Challenger Coacing Canvas"
theme = "hugo-universal-theme"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
googleAnalytics = "UA-1385956-25"

[[menu.main]]
    name = "Домой"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Путеводитель"
    url  = "/guide"
    weight = 2

[[menu.main]]
    name = "Дополнительно"
    url  = "/materials"
    weight = 3

[[menu.main]]
    name = "Задайте вопрос"
    url  = "/contact"
    weight = 3

[[menu.main]]
    name = "О нас"
    url  = "/about"
    weight = 4

[params]
    copyright = "Creative Commons Attribution 4.0 International license"
    logo = "none"
    email = "integral-foxes@googlegroups.com"


[params.carousel]
    enable = true
