baseurl = "/"
title = "Challenger Coacing Canvas"
theme = "hugo-universal-theme"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
googleAnalytics = "UA-1385956-25"

[[menu.main]]
    name = "Домой"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Путеводитель"
    url  = "/guide"
    weight = 2

[[menu.main]]
    name = "Задайте вопрос"
    url  = "/contact"
    weight = 3

[[menu.main]]
    name = "О нас"
    url  = "/about"
    weight = 4

[[menu.main]]
    name = "Лисьи истории"
    url  = "/blog"
    weight = 5

[params]
    copyright = "&nbsp;&nbsp;challengercoachingcanvas.online"
    logo = "none"
    email = "integral-foxes@googlegroups.com"
    date_format = "January 2, 2006"


[params.carousel]
    enable = true
